nginxplus:
  build: nginx
  container_name: nginxplus
  ports:
  - "80:80"
  - "8080:8080"
  volumes:
  - "./nginx/app.conf:/etc/nginx/conf.d/app.conf"
  - "./nginx/services/:/etc/nginx/conf.d/services/"

consul:
  command: "-server -bootstrap -node consul -advertise ${HOST_IP} -config-file /etc/consul.d/config.json"
  image: progrium/consul:latest
  container_name: consul
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
  volumes:
  - "./consul_watches_config.json:/etc/consul.d/config.json"
  - "./registerderegister.sh:/tmp/registerderegister.sh"
  environment:
  - HOST_IP

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  container_name: registrator
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

